[versions]
kotlin = "2.1.10"
android_gradle_plugin = "8.7.2"
koin = "4.0.1"
ksp = "2.1.10-1.0.29"

dokka = "1.9.10"
detekt = "1.23.6"
compose_plugin_multiplataform = "1.7.3"
navigation-compose-version = "2.7.0-alpha07"
paging-compose = "3.3.0-alpha02-0.5.1"
buildkonfig = "0.15.2"
cameraCore = "1.4.2"
moko-permissions = "0.19.1"

#Test
test_junit = "4.13.2"
androidx_core_testing = "2.2.0"
mockk = "1.13.7"
kotlinx-coroutines = "1.8.1"

#Networking
okhttp = "4.12.0"
ktor = "3.0.1"

coil = "3.1.0"
lottie = "5.2.0"

#Room Database
room = "2.7.0-alpha13"
sqlite = "2.5.0-SNAPSHOT"
core-ktx = "1.15.0"
junit = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
accompanist = "0.31.3-beta"
activity-compose = "1.8.2"

popcorngp = "3.1.2"

[libraries]
kotlin_gradle_plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android_gradle_plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android_gradle_plugin" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
serialization = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }

com-google-devtools-ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref="coil"}

lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

kotlin_stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }

navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose-version" }
paging-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "paging-compose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

#Camera
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }

# Koin
koin_test = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koin" }
koin_android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin_core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin_compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin_compose_viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

#Networking
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

ktor_client_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_client_okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor_client_logger = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor_client_auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor_client_darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor_client_content_negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_client_content_serialization_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

#MOKO
moko-permissions-core = { module = "dev.icerock.moko:permissions", version.ref = "moko-permissions" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko-permissions" }
moko-permissions-camera = { module = "dev.icerock.moko:permissions-camera", version.ref = "moko-permissions" }
moko-permissions-gallery = { module = "dev.icerock.moko:permissions-gallery", version.ref = "moko-permissions" }

#Room
room_runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room_bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

dokka = { group = "org.jetbrains.dokka", name = "android-documentation-plugin", version.ref = "dokka" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity-compose = { module = "androidx.activity:activity-compose", version = "activity-compose" }

#Test
kotlin_test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin_test_common = { group = "org.jetbrains.kotlin", name = "kotlin-test-common", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "test_junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk_android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
viewmodel_test = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidx_core_testing" }
coroutines_test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

popcorn_guineapig = { group = "io.github.codandotv", name = "popcornguineapig", version.ref = "popcorngp" }

[bundles]
test = ["junit", "mockk", "mockk_android", "viewmodel_test", "koin_test", "coroutines_test"]
test_multiplatform = ["kotlin_test", "kotlin_test_common", "coroutines_test",]
camera = [
    "androidx-camera-camera2",
    "androidx-camera-core",
    "androidx-camera-lifecycle",
    "androidx-camera-view"
]

[plugins]
android_application = { id = "com.android.application", version.ref = "android_gradle_plugin" }
android_library = { id = "com.android.library", version.ref = "android_gradle_plugin" }

kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose_plugin_multiplataform" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose_compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

buildkonfig_plugin = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
